### ISSUE TITLE
FIN108 - Revitalização Credito [ Montadora ]

### ISSUE THREAD

**Issue by evandromariano** [Caoa-Montadora-de-Veiculos-Ltda/Protheus#14]
- [ ] Implementação do controle de crédito no cadastro do cliente.
- [ ] Retirar os pontos de entrada que tratam o limite de crédito padrão/customizado projeto
- [ ] Implementar o limite de crédito no faturamento
- [ ] Verificar se o relatório de limite de crédito está funcionando para montadora.
- [ ] Ajustar e revitalizar o controle de log de alteração do limite de crédito.
- [ ] Criar um botão Consulta Log de Alteração do Crédito do cliente

**Pontos de Atenção**

1.  Não pode controlar limite de crédito no faturamento veículos.
2. Precisa ter a regra de não controlar limite de crédito na cond. de pagamento a vista emergencial (Igual Barueri)
3. Controlar limite de crédito de todas as cond que geram titulo no financeiro. Exceto Veiculos

**Comment by dacdenilso-work** [comment]
[FIN108 - Revitalização Limite de Crédito Montadora.docx](https://github.com/Caoa-Montadora-de-Veiculos-Ltda/Protheus/files/11409721/FIN108.-.Revitalizacao.Limite.de.Credito.Montadora.docx)
[FIN108 - Revitalização Limite de Crédito Montadora.xlsx](https://github.com/Caoa-Montadora-de-Veiculos-Ltda/Protheus/files/11409722/FIN108.-.Revitalizacao.Limite.de.Credito.Montadora.xlsx)

**Comment by dacdenilso-work** [comment]
[Termo FIN108 - Revitalização Limite de Crédito Montadora.docx](https://github.com/Caoa-Montadora-de-Veiculos-Ltda/Protheus/files/11410249/Termo.FIN108.-.Revitalizacao.Limite.de.Credito.Montadora.docx)
