### ISSUE TITLE
Integração | RgLog 004.001 | Envio integração nota de entrada por marca

### ISSUE THREAD

**Issue by evandromariano** [Caoa-Montadora-de-Veiculos-Ltda/Protheus#146]
**PEC069 - Envio integração nota de entrada por marca [ INTEGRAÇÃO ]**
**Objetivo:** Esse Gap tem como objetivo ajustar o fonte ZWSR010 para que as integrações sejam enviadas para a RgLog por marca. Caso a nota tenha 10 itens sendo 5 Chery e 5 Hyundai, será necessario o envio de 2 integrações. Uma contendo os 5 itens da Chery e outra contendo 5 itens da Hyundai.

**Termo de Entrega:**

**Comment by dacdenilso-work** [comment]
[GAP020  Envio integração nota de entrada por marca \[ INTEGRAÇÃO \]_TERMO.pdf](https://github.com/Caoa-Montadora-de-Veiculos-Ltda/Protheus/files/14345715/GAP020.Envio.integracao.nota.de.entrada.por.marca.INTEGRACAO._TERMO.pdf)
