### ISSUE TITLE
PEC004.001 | Ajuste itens similar

### ISSUE THREAD

**Issue by evandromariano** [Caoa-Montadora-de-Veiculos-Ltda/Protheus#147]

**Comment by dacdenilso-work** [comment]
Fonte: ZPECF030
Erro: Falta item Similar
Correção01: Incluido funcionalidade ZPECF30ITS na tela principal
Erro: Calculo de Saldo e de orçamento duplicando
Correção02: Ajustado Select na subquery para verificar B2_local, mostrar todos os armazens com saldos, e mostrar sempre armazém 11 mesmo sem saldo

Fonte: ZPECFUNA
Erro: Confirmação na consulta do orçamento errolog
Correção01: Criado funcionalidade para consulta de Orçamento MILAXTABELA e retirada antiga

Fonte: ZPECF032
Erro: Confirmação na consulta do orçamento errolog
Correção01: Alterado botão para consulta de Orçamento chamada fonte MILAXTABELA
