### ISSUE TITLE
EIC007 | Integração Ásia Shipping

### ISSUE THREAD

**Issue by evandromariano** [Caoa-Montadora-de-Veiculos-Ltda/Protheus#179]

**Comment by Antoniopoliveira** [comment]
[Manual_Tecnico_Integração_ASIA.pdf](https://github.com/Caoa-Montadora-de-Veiculos-Ltda/Protheus/files/13170325/Manual_Tecnico_Integracao_ASIA.pdf)
[Termo_Entrega-EIC122_Integração_ASIA.pdf](https://github.com/Caoa-Montadora-de-Veiculos-Ltda/Protheus/files/13170326/Termo_Entrega-EIC122_Integracao_ASIA.pdf)



[Fontes.zip](https://github.com/Caoa-Montadora-de-Veiculos-Ltda/Protheus/files/13170333/Fontes.zip)
