### ISSUE TITLE
EIC006 | Relatório de detalhamento de Invoices

### ISSUE THREAD

**Issue by evandromariano** [Caoa-Montadora-de-Veiculos-Ltda/Protheus#193]

**Comment by NicLima** [comment]
**Analista Funcional:** Luis Takahashi
**Validação:** Luis Takahashi

**Fonte**: ZEICR003
**Motivo:** Desenvolvimento de um novo relatório detalhar as informações de invoices.

**Especificação Funcional:** [INC0093591 Especificação de personalização Relatório de Detalhamento de Invoices.pdf](https://github.com/Caoa-Montadora-de-Veiculos-Ltda/Protheus/files/12475044/INC0093591.Especificacao.de.personalizacao.Relatorio.de.Detalhamento.de.Invoices.pdf)
**Termo de Entrega:** 
**Manual:**[Manual de validação - GAP053  Relatório de detalhamento de invoices..docx](https://github.com/Caoa-Montadora-de-Veiculos-Ltda/Protheus/files/12475052/Manual.de.validacao.-.GAP053.Relatorio.de.detalhamento.de.invoices.docx)
