### ISSUE TITLE
MNT001 | Relatório Arvore Logica

### ISSUE THREAD

**Issue by evandromariano** [Caoa-Montadora-de-Veiculos-Ltda/Protheus#207]

**Comment by Antoniopoliveira** [comment]
[GAP033_Manual_Tecnico_Arvore_Logica.pdf](https://github.com/Caoa-Montadora-de-Veiculos-Ltda/Protheus/files/12714684/GAP033_Manual_Tecnico_Arvore_Logica.pdf)
[GAP033-Termo_Entrega.pdf](https://github.com/Caoa-Montadora-de-Veiculos-Ltda/Protheus/files/12714685/GAP033-Termo_Entrega.pdf)
