### ISSUE TITLE
Integração | Autoware 100.005 | Erro na abertura da empresa no momento do recebimento.

### ISSUE THREAD

**Issue by evandromariano** [Caoa-Montadora-de-Veiculos-Ltda/Protheus#231]
Fonte: CMVAUT01
Erro: Em alguns casos estava apresentando erro de falta de modelo.
Correção: Ajustado o fonte para sempre conectar na empresa 01 - Montadora Anapolis no momento do recebimento da integração

**Comment by reirabelo** [comment]
**Termo de Entrega**
[GAP067 -Erro na abertura da empresa no momento do recebimento.pdf](https://github.com/Caoa-Montadora-de-Veiculos-Ltda/Protheus/files/12303810/GAP067.-Erro.na.abertura.da.empresa.no.momento.do.recebimento.pdf)
