### ISSUE TITLE
COM003.001 | Adicionado observação geral e modificado observação do fornecedor.

### ISSUE THREAD

**Issue by evandromariano** [Caoa-Montadora-de-Veiculos-Ltda/Protheus#248]

**Comment by NicLima** [comment]
**Analista Funcional:** Thaynara Alves Pimentel

**Validação:** Thaynara Alves Pimentel

**Fonte:** ZCOMR001

**Motivo:** Movimentar para cima a informação que vem do campo C7_XOBSFOR e mudar o campo de origem das "Observações gerais" do PDF do pedido de compra para C7_XOBSCOM.

**Especificação Funcional:** [COM136 - Melhorias no envio do pedido de compras.pdf](https://github.com/Caoa-Montadora-de-Veiculos-Ltda/Protheus/files/12623685/COM136.-.Melhorias.no.envio.do.pedido.de.compras.pdf)

**Termo de Entrega:** [Termo de entrega - GAP073  Melhoria no envio de pedido de compra.docx](https://github.com/Caoa-Montadora-de-Veiculos-Ltda/Protheus/files/12623688/Termo.de.entrega.-.GAP073.Melhoria.no.envio.de.pedido.de.compra.docx)

**Manual:** [Manual de validação - GAP073  Melhoria no envio de pedido de compra.docx](https://github.com/Caoa-Montadora-de-Veiculos-Ltda/Protheus/files/12623689/Manual.de.validacao.-.GAP073.Melhoria.no.envio.de.pedido.de.compra.docx)
