### ISSUE TITLE
VEI002 | Ajuste no parâmetro de comissão de venda

### ISSUE THREAD

**Issue by evandromariano** [Caoa-Montadora-de-Veiculos-Ltda/Protheus#256]
**CHG003339 | VEIA060CAOA_001 | Parâmetro de comissão de venda**

**Descrição:** Criação de parâmetro para o Pedido de Venda de Veículo específico para % de comissão

**Especificação Técnica:** [FIS 117- Especificação Funcional - Parametro Venda Direta.pdf](https://github.com/Caoa-Montadora-de-Veiculos-Ltda/Protheus/files/13226359/FIS.117-.Especificacao.Funcional.-.Parametro.Venda.Direta.pdf)
**Manual Técnico:** [GAP077-Manual_Técnico.pdf](https://github.com/Caoa-Montadora-de-Veiculos-Ltda/Protheus/files/13226361/GAP077-Manual_Tecnico.pdf)
**Termo de Entrega: [Termo_Entrega - GAP077 - Parametro Venda Direta.pdf](https://github.com/Caoa-Montadora-de-Veiculos-Ltda/Protheus/files/14736576/Termo_Entrega.-.GAP077.-.Parametro.Venda.Direta.pdf)

**Comment by Antoniopoliveira** [comment]
GAP077 - Parâmetro de Comissão de Venda
                Criação de parâmetro para o Pedido de Venda de Veículo específico para % de comissão
Solicitante: Montilha - Totvs
Desenvolvedor: A.Carlos - CAOA
Data: 06/10/2023
[FIS 117- Especificação Funcional - Parametro Venda Direta.pdf](https://github.com/Caoa-Montadora-de-Veiculos-Ltda/Protheus/files/13226359/FIS.117-.Especificacao.Funcional.-.Parametro.Venda.Direta.pdf)
[GAP077-Manual_Técnico.pdf](https://github.com/Caoa-Montadora-de-Veiculos-Ltda/Protheus/files/13226361/GAP077-Manual_Tecnico.pdf)
