### ISSUE TITLE
EIC003.011 | Excluir SZM após estorno da Invoice

### ISSUE THREAD

**Issue by evandromariano** [Caoa-Montadora-de-Veiculos-Ltda/Protheus#265]

**Comment by NicLima** [comment]
**Analista Funcional:** Luís Fernando Takashi

**Validação:** Luís Fernando Takashi

**Fontes:**
CMVEIC01
ZEICF021
ZEICF024
ZCOMF051

**Motivo:** Criar um botão que para limpar registros na tabela SZM que são resquícios de Invoices antecipadas que já foram estornados e apagados em tabelas EW4 e EW5.
E garantir que os fontes ZEICF021, CMVEIC01 e ZCOMF051 gravem o campo SZM.R_E_C_D_E_L_ = SZM.R_E_C_N_O_.

Especificação Funcional: [SIGAEIC Especificação de personalização Invoice Antecipada..docx](https://github.com/Caoa-Montadora-de-Veiculos-Ltda/Protheus/files/12753745/SIGAEIC.Especificacao.de.personalizacao.Invoice.Antecipada.docx)

Termo de Entrega: [Termo de entrega - GAP082 Excluir SZM na exclusão da Invoice Antecipada..docx](https://github.com/Caoa-Montadora-de-Veiculos-Ltda/Protheus/files/12753756/Termo.de.entrega.-.GAP082.Excluir.SZM.na.exclusao.da.Invoice.Antecipada.docx)

Manual:  [Manual de validação - GAP082 Excluir SZM na exclusão da Invoice Antecipada..docx](https://github.com/Caoa-Montadora-de-Veiculos-Ltda/Protheus/files/12753757/Manual.de.validacao.-.GAP082.Excluir.SZM.na.exclusao.da.Invoice.Antecipada.docx)
