### ISSUE TITLE
PEC010.001 | Ajustado para usar novo layout Valor e Moeda FOB

### ISSUE THREAD

**Issue by evandromariano** [Caoa-Montadora-de-Veiculos-Ltda/Protheus#266]

**Comment by Antoniopoliveira** [comment]
Incluído a opção de importar apenas Valor e Moeda FOB usando lay-out : Produto, Valor, Moeda
[Fontes.zip](https://github.com/Caoa-Montadora-de-Veiculos-Ltda/Protheus/files/12601052/Fontes.zip)

**Comment by Antoniopoliveira** [comment]
GAP083 - Importação Lista FOB
Fonte: ZPECF037 - Função p/importar Valor e Moeda FOB - Franco da Rocha
Autor: A.Carlos - CAOA
Solicitante: José Carlos - TOTVS

[Fontes.zip](https://github.com/Caoa-Montadora-de-Veiculos-Ltda/Protheus/files/12741259/Fontes.zip)



[GAP083 - Importação Lista FO_Manual_Tecnico.pdf](https://github.com/Caoa-Montadora-de-Veiculos-Ltda/Protheus/files/12741262/GAP083.-.Importacao.Lista.FO_Manual_Tecnico.pdf)



[Termo_Entrega - GAP083 - Importação lista FOB.docx](https://github.com/Caoa-Montadora-de-Veiculos-Ltda/Protheus/files/12741265/Termo_Entrega.-.GAP083.-.Importacao.lista.FOB.docx)
