### ISSUE TITLE
MNT001.001 | Ativo sem Estrutura Cadastrada na Árvore Lógica

### ISSUE THREAD

**Issue by evandromariano** [Caoa-Montadora-de-Veiculos-Ltda/Protheus#278]

**Comment by Antoniopoliveira** [comment]
GAP088 - Ativo sem Estrutura Cadastrada na Árvore Lógica
Fonte: ZMNTR004 - Ajustada a função p/gerar o relatório da Árvore Lógica de itens de manutenção Anápolis
Autor: A.Carlos - CAOA
Solicitante: Thaynara - CAOA


[ZMNTR004.zip](https://github.com/Caoa-Montadora-de-Veiculos-Ltda/Protheus/files/12739443/ZMNTR004.zip)
[GAP088-Termo_Entrega.pdf](https://github.com/Caoa-Montadora-de-Veiculos-Ltda/Protheus/files/12739455/GAP088-Termo_Entrega.pdf)
