### ISSUE TITLE
COM004 | Validação do comprador desligado

### ISSUE THREAD

**Issue by evandromariano** [Caoa-Montadora-de-Veiculos-Ltda/Protheus#288]

**Comment by NicLima** [comment]
**Analista Funcional:**  Thaynara Alves Pimentel

**Validação:** Thaynara Alves Pimentel

**Fonte:** MT110TOK - Alterado
**Ajuste:** Ponto de entrada acionado ao salvar a solicitação de compras.

**Fonte:** ZCOMF055 - Novo
**Ajuste:** Fonte responsável para verificar se o código de comprador e um usuário bloqueado.  

**Fonte:** ZCOMF056 - Novo
**Ajuste:** Fonte responsável por consulta padrão específica dos códigos de compradores desbloqueados.

**Especificação Funcional:** [COM133 - Adicionar mensagem de comprador desligado.pdf](https://github.com/Caoa-Montadora-de-Veiculos-Ltda/Protheus/files/12920542/COM133.-.Adicionar.mensagem.de.comprador.desligado.pdf)

**Termo de Entrega:** [Termo de entrega - GAP091 - Adicionar validação de comprador desligado..docx](https://github.com/Caoa-Montadora-de-Veiculos-Ltda/Protheus/files/12920550/Termo.de.entrega.-.GAP091.-.Adicionar.validacao.de.comprador.desligado.docx)

**Manual:** [Manual de validação - GAP091 - Adicionar validação de comprador desligado..docx](https://github.com/Caoa-Montadora-de-Veiculos-Ltda/Protheus/files/12920551/Manual.de.validacao.-.GAP091.-.Adicionar.validacao.de.comprador.desligado.docx)
