### ISSUE TITLE
COM005 | Habilitar a tela de aprovadores de solicitação de compras

### ISSUE THREAD

**Issue by evandromariano** [Caoa-Montadora-de-Veiculos-Ltda/Protheus#306]

**Comment by NicLima** [comment]
**Analista:** Thaynara Alves Pimentel
**Validação:**  Thaynara Alves Pimentel

**Objetivo:** Habilitar a tela de “Log Aprov” para consultar o status das alçadas de aprovação nas Solicitações de Compras.

**Especificação Funcional:** [COM141 - Incluir a opção de aprovador na solicitação de compras.docx](https://github.com/Caoa-Montadora-de-Veiculos-Ltda/Protheus/files/13308675/COM141.-.Incluir.a.opcao.de.aprovador.na.solicitacao.de.compras.docx)

**Manual de validação:** [Manual de validação - GAP097 Habilitar tela de log aprov. para consultar aprovações nas SCs.docx](https://github.com/Caoa-Montadora-de-Veiculos-Ltda/Protheus/files/13308711/Manual.de.validacao.-.GAP097.Habilitar.tela.de.log.aprov.para.consultar.aprovacoes.nas.SCs.docx)

**Termo de Entrega:** [Termo de entrega - GAP097 Habilitar tela de log aprov. para consultar aprovações nas SCs.docx](https://github.com/Caoa-Montadora-de-Veiculos-Ltda/Protheus/files/13308716/Termo.de.entrega.-.GAP097.Habilitar.tela.de.log.aprov.para.consultar.aprovacoes.nas.SCs.docx)
