### ISSUE TITLE
GAP119 | Demonstrar saldo e custo do produto na Ord Serv Corretiva

### ISSUE THREAD

**Issue by evandromariano** [Caoa-Montadora-de-Veiculos-Ltda/Protheus#355]
**GAP119 | Demonstrar saldo e custo do produto na Ord Serv Corretiva**
**Melhoria:** Solicitação feita pelo setor de manutenção, para que seja possivel visualizar o o saldo atual e o custo unitario do produto.
**Analista Funcional:** Thaynara Alves Pimentel <thaynara.pimentel@caoamontadora.com.br>
**Especificação Funcional:** [GAP119 - Demonstrar saldo e custo do produto na Ord Serv Corretiva.pdf](https://github.com/Caoa-Montadora-de-Veiculos-Ltda/Protheus/files/13842335/GAP119.-.Demonstrar.saldo.e.custo.do.produto.na.Ord.Serv.Corretiva.pdf)
**Manual:** [Manual_Técnico - GAP119 - Demonstrar saldo e custo do produto na Ord. Serv. Corretiva.docx](https://github.com/Caoa-Montadora-de-Veiculos-Ltda/Protheus/files/13845569/Manual_Tecnico.-.GAP119.-.Demonstrar.saldo.e.custo.do.produto.na.Ord.Serv.Corretiva.docx)

**Termo de Entrega:[Termo de Entrega - GAP119 - Demonstrar.saldo.e.custo.do.produto.na.Ord.Serv.Corretiva.docx](https://github.com/Caoa-Montadora-de-Veiculos-Ltda/Protheus/files/13845580/Termo.de.Entrega.-.GAP119.-.Demonstrar.saldo.e.custo.do.produto.na.Ord.Serv.Corretiva.docx)

**Comment by sandroferreira2009** [comment]
Criado dois campos virtuais 
TL_VATU1   -  Saldo Atual 
Criado um posicione para buscar o saldo atual na tabela SB2010 para o armazém 181  
TL_CM1       - Custo Unitário
Criado um posicione para buscar o Custo Unitário na tabela SB2010 para o armazém 181

**Comment by sandroferreira2009** [comment]
[GAP119.zip](https://github.com/Caoa-Montadora-de-Veiculos-Ltda/Protheus/files/14311713/GAP119.zip)
