### ISSUE TITLE
PEC013.001 | Ajuste nas CFOPs de entrada e saida

### ISSUE THREAD

**Issue by evandromariano** [Caoa-Montadora-de-Veiculos-Ltda/Protheus#360]
**Tarefa 01 - Aplicar update para atualizar as datas do legado**
Update SB1: [Tarefa 01 - Update Ajuste das Datas do Legado.txt](https://github.com/Caoa-Montadora-de-Veiculos-Ltda/Protheus/files/14102154/Tarefa.01.-.Update.Ajuste.das.Datas.do.Legado.txt)

**Tarefa 02 - Aplicar update para ajustar os parametros da CFOP**
Update SX6: 

Atualização parametro

![Image](https://github.com/Caoa-Montadora-de-Veiculos-Ltda/Protheus/assets/127143346/ed039ad7-05d2-47e9-b301-7aae20c47421)

**Comment by dacdenilso-work** [comment]
Alterado Select do retorno SD1 no Join SF4 controlara se atualiza Estoque que SER "S"
Wandre informou que as notas de importado não estão trazendo data, após avaliar verificado que a CFOP constante no parâmetro esta relacionada a CFP da Nota Mãe que não movimenta Estoque, nas notas filhas é que estão movimentando estoque, Wandre solicitou atualizar parâmetro com nova CFOP que consta nas notas filhas
