### ISSUE TITLE
COM009 | Alteração Lote e Sublote Nota de Entrada

### ISSUE THREAD

**Issue by evandromariano** [Caoa-Montadora-de-Veiculos-Ltda/Protheus#363]
**GAP124 | Alteração Lote e Sublote Nota de Entrada**

**Descrição:** Foi validado junto a TOTVS que hoje os campos LOTE e SUBLOTE são campos preenchidos durante a entrada da NF (mata103), assim que classificado a NF, 4 tabelas recebem as informações da NOTA  (SD1,D14,SB8,SD5) para os campos de lote e sublote quando houver. 
Essa melhoria tem por finalidade permitir a área de logística o controle do lote do material recebido apos endereçamento e, permitir ajustar o lote de entrada antes da classificação da NFe. 

**Especificação Técnica:** [DEV17 - Especificação Funcional -Alteraçao de LOTES.docx](https://github.com/Caoa-Montadora-de-Veiculos-Ltda/Protheus/files/14362579/DEV17.-.Especificacao.Funcional.-Alteracao.de.LOTES.docx)
**Manual Técnico:** [Manual_Técnico-GAP124-Alteração_Lote.pdf](https://github.com/Caoa-Montadora-de-Veiculos-Ltda/Protheus/files/14362580/Manual_Tecnico-GAP124-Alteracao_Lote.pdf)
**Termo de Entrega:** [Termo_Entrega_GAP124 – Alteração_Lote.pdf](https://github.com/Caoa-Montadora-de-Veiculos-Ltda/Protheus/files/14362586/Termo_Entrega_GAP124.Alteracao_Lote.pdf)

**Comment by Antoniopoliveira** [comment]
Fontes: 
[zestf015.zip](https://github.com/Caoa-Montadora-de-Veiculos-Ltda/Protheus/files/14363325/zestf015.zip)
