### ISSUE TITLE
GAP135 | Ajuste no campo de custo do relatorio do Manutenção

### ISSUE THREAD

**Issue by evandromariano** [Caoa-Montadora-de-Veiculos-Ltda/Protheus#383]
**GAP135 | Ajuste no campo de custo do relatorio do Manutenção**

**Descrição:** Melhoria no relatório sintético estoque/compras para alterar o valor de custo médio que estava buscando da tabela SB2, porém o custo médio do último fechamento consta na tabela SB9. 

**Especificação Técnica:** Não possui
**Manual Técnico: [Manual_Tecnico - GAP134 REL Cad Produto - Sintetico.docx](https://github.com/Caoa-Montadora-de-Veiculos-Ltda/Protheus/files/14408251/Manual_Tecnico.-.GAP134.REL.Cad.Produto.-.Sintetico.docx)

**Termo de Entrega: [Termo_Entrega - GAP135 - Cuso Médio Cad Produto - Sintético.pdf](https://github.com/Caoa-Montadora-de-Veiculos-Ltda/Protheus/files/14408254/Termo_Entrega.-.GAP135.-.Cuso.Medio.Cad.Produto.-.Sintetico.pdf)

**Comment by Antoniopoliveira** [comment]
Fontes: [ZMNTR002.zip](https://github.com/Caoa-Montadora-de-Veiculos-Ltda/Protheus/files/14408271/ZMNTR002.zip)
