### ISSUE TITLE
FIN003.003 | Ajuste na mensagem de liberacao de credito

### ISSUE THREAD

**Issue by NicLima** [Caoa-Montadora-de-Veiculos-Ltda/Protheus#391]
GAP140 | Rotina de pedido de venda

**Descrição:** Ao preparar doc. saída a tela trava em avaliação do limite de crédito.

**Especificação Técnica:** [Rotina Pedido de Venda.pdf](https://github.com/Caoa-Montadora-de-Veiculos-Ltda/Protheus/files/14560023/Rotina.Pedido.de.Venda.pdf)

**Manual Técnico:** Não Possui
**Termo de Entrega:**  [GAP140 - Travamento na Avaliação de Credito do Cliente.pdf](https://github.com/Caoa-Montadora-de-Veiculos-Ltda/Protheus/files/14672692/GAP140.-.Travamento.na.Avaliacao.de.Credito.do.Cliente.pdf)

**Comment by reirabelo** [comment]
Alteração no ponto de entrada M410PVNF_PE.prw a exibição de mensagem da liberação de crédito, para aparecer somente quando o Credito for negado, e alteração para uma função mais atual para exibição de mensagens.
Alteração do fonte ZFATF014.prw, removendo funções no momento da gravação da Tabela SA1, e reposicionando antes da gravação da tabela.
