### ISSUE TITLE
GAP192 | Ajustes Portal Comercial V01

### ISSUE THREAD

**Issue by Antoniopoliveira** [Caoa-Montadora-de-Veiculos-Ltda/Protheus#503]
GAP191 - Ajustes Portal Comercial V01

*Descrição:* Descrição resumida 

*Especificação Técnica:* Não possui
*Manual Técnico:* Não Possui
*Termo de Entrega:* Não Possui

**Comment by dacdenilso-work** [comment]
Melhoria filtrar o processo por cliente e produto, anteriormente estava tratando pedido autoware como uma das chaves principais
