### ISSUE TITLE
GAP195 | Erro ao integrar invoice antecipada - CBU Chery

### ISSUE THREAD

**Issue by reirabelo** [Caoa-Montadora-de-Veiculos-Ltda/Protheus#507]
GAP195 | Erro ao integrar invoice antecipada - CBU Chery

Descrição:
Erro na criação do índice ao integrar invoice antecipada - CBU Chery

Solução:
Alteração na criação da tabela temporária de DbUseArea para FWTemporaryTable, na função MontaWork1 do fonte CMVEIC01.prw na linha 817.

Especificação Técnica: Não Possui
Manual Técnico: Não Possui
Termo de Entrega: 

[GAP195_INC0114843.pdf](https://github.com/user-attachments/files/15841955/GAP195_INC0114843.pdf)

**Comment by Antoniopoliveira** [comment]
Aprovado em Produção
