### ISSUE TITLE
GAP221 - Incluir campo de grupo de cliente e fornecedor nos relatórios fiscais ZFISR001 e ZFISR004 - INC0113977

### ISSUE THREAD

**Issue by Ajunior12** [Caoa-Montadora-de-Veiculos-Ltda/Protheus#557]
GAP221 - Incluir campo de grupo de cliente e fornecedor nos relatórios fiscais ZFISR001 e ZFISR004 - INC0113977

Descrição: Toninho, houve um erro na inclusão de um campo no relatório do Fiscal, ao invés de ser incluído o campo de GRP CLIENTES no relatório ZFISR004, foi no ZFISR003 não que haja problema, mas era pra ser incluso no ZFISR004 também, como nos outros dois já foram aplicados precisava incluir no relatório ZFISR004, segue especificação em anexo.

Especificação Técnica: [ESPECIFICAÇÃO CLIENTES E FORNECEDORES.pdf](https://github.com/user-attachments/files/16336958/ESPECIFICACAO.CLIENTES.E.FORNECEDORES.pdf)
Manual Técnico: Não Possui
Termo de Entrega: Não Possui

**Comment by Antoniopoliveira** [comment]
Fundido no GAP218
