### ISSUE TITLE
GAP004 | Faturamento Automático

### ISSUE THREAD

**Issue by evandromariano** [Caoa-Montadora-de-Veiculos-Ltda/Protheus#61]

**Comment by dacdenilso-work** [comment]
Funcionalidade ZPECF036 criada para Faturamento Automático, o processo será tratado no GAP002

**Comment by dacdenilso-work** [comment]
[GAP002  Integração da separação - Informar produto e quantidade da cubagem_V3.docx](https://github.com/Caoa-Montadora-de-Veiculos-Ltda/Protheus/files/12686041/GAP002.Integracao.da.separacao.-.Informar.produto.e.quantidade.da.cubagem_V3.docx)

**Comment by dacdenilso-work** [comment]
[Uploading GAP002  Integração da separação - Informar produto e quantidade da cubagem_V3.docx…]()

**Comment by NicLima** [comment]
**Incorporado ao GAP098 | Revitalização da Onda de Pedidos Versão 3.0**
