### ISSUE TITLE
PEC013 | Cálculo da Curva ABC

### ISSUE THREAD

**Issue by evandromariano** [Caoa-Montadora-de-Veiculos-Ltda/Protheus#69]

**Comment by dacdenilso-work** [comment]
[ESPFUNC - PEC057 - Cálculo da Curva ABC Termo.pdf](https://github.com/Caoa-Montadora-de-Veiculos-Ltda/Protheus/files/13181964/ESPFUNC.-.PEC057.-.Calculo.da.Curva.ABC.Termo.pdf)
[ESPFUNC - PEC057 - Cálculo da Curva ABC.pdf](https://github.com/Caoa-Montadora-de-Veiculos-Ltda/Protheus/files/13181967/ESPFUNC.-.PEC057.-.Calculo.da.Curva.ABC.pdf)
[PEC057 - Cálculo da Curva ABC_GAP014_V1.pdf](https://github.com/Caoa-Montadora-de-Veiculos-Ltda/Protheus/files/13181968/PEC057.-.Calculo.da.Curva.ABC_GAP014_V1.pdf)
[UPD_GAP014_CurvaABC.zip](https://github.com/Caoa-Montadora-de-Veiculos-Ltda/Protheus/files/13181980/UPD_GAP014_CurvaABC.zip)

**Comment by dacdenilso-work** [comment]
[Update_GAP014.zip](https://github.com/Caoa-Montadora-de-Veiculos-Ltda/Protheus/files/13254859/Update_GAP014.zip)

**Comment by dacdenilso-work** [comment]
Atualização update

**Comment by dacdenilso-work** [comment]
[Validação_Finalizada.pdf](https://github.com/Caoa-Montadora-de-Veiculos-Ltda/Protheus/files/13254887/Validacao_Finalizada.pdf)
