### ISSUE TITLE
GFE101 - Ajuste no cálculo de novos componentes

### ISSUE THREAD

**Issue by evandromariano** [Caoa-Montadora-de-Veiculos-Ltda/Protheus#96]

**Comment by Antoniopoliveira** [comment]
[Manual_Técnico_GFE101-Ajuste_Calculo_Novos_Componentes.pdf](https://github.com/Caoa-Montadora-de-Veiculos-Ltda/Protheus/files/11738427/Manual_Tecnico_GFE101-Ajuste_Calculo_Novos_Componentes.pdf)
[Termo_Entrega - GFE101 – Ajuste Cálculo Novos Componentes.pdf](https://github.com/Caoa-Montadora-de-Veiculos-Ltda/Protheus/files/11738428/Termo_Entrega.-.GFE101.Ajuste.Calculo.Novos.Componentes.pdf)
[Fontes.zip](https://github.com/Caoa-Montadora-de-Veiculos-Ltda/Protheus/files/11738429/Fontes.zip)
